[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["cd news-aggregator && pip install -r requirements.txt"]

[start]
cmd = "cd news-aggregator && gunicorn --bind 0.0.0.0:$PORT --timeout 120 app:app"
